import type { Theme, ThemeId } from './types';
import { pick, rand, type Rng } from './rng';

export const SCRIPTED_THEMES: Theme[] = [
    {
        id: 'ufo',
        name: 'Visitors',
        subtitle: 'Unidentified Aerial Phenomena',
        wallColor: '#c7cdd0',
        accentColor: '#4fc3f7',
        floorMaterial: 'tile',
        lightColor: '#dff3ff',
        lightIntensity: 1.1,
        ceiling: 5.2,
        font: 'space-mono',
        titleLetterSpacing: 0.25,
        audioTone: {
            baseHz: 58,
            partials: [1, 2.01, 3.02],
            lfoHz: 0.06,
            noiseCenterHz: 1800,
            noiseGain: 0.05,
            bellRatio: 7.5,
            bellEverySec: 22,
        },
        infographic: {
            title: 'KNOWN SIGHTINGS',
            body: [
                '1947 - Roswell, NM',
                '1952 - D.C. flyover',
                '1967 - Shag Harbour',
                '1980 - Rendlesham',
                '1997 - Phoenix Lights',
                '2004 - Tic Tac / Nimitz',
                '',
                'the sky is a mirror.',
                'what looked back was waiting.',
            ],
        },
    },
    {
        id: 'ai-history',
        name: 'Thinking Machines',
        subtitle: 'A brief history of artificial minds',
        wallColor: '#d8d2c4',
        accentColor: '#ffb74d',
        floorMaterial: 'vinyl',
        lightColor: '#fff4d6',
        lightIntensity: 1.0,
        ceiling: 4.6,
        font: 'plex-mono',
        titleLetterSpacing: 0.15,
        audioTone: {
            baseHz: 72,
            partials: [1, 1.5, 2.0, 3.0],
            lfoHz: 0.09,
            noiseCenterHz: 2200,
            noiseGain: 0.04,
            bellRatio: 6,
            bellEverySec: 18,
        },
        infographic: {
            title: 'A HISTORY OF THOUGHT',
            body: [
                '1936  Turing machine',
                '1943  McCulloch-Pitts',
                '1956  Dartmouth',
                '1957  Perceptron',
                '1986  Backpropagation',
                '1997  Deep Blue',
                '2012  AlexNet',
                '2017  Attention',
                '2022  ChatGPT',
                '',
                'we built a mirror',
                'that dreamed.',
            ],
        },
    },
    {
        id: 'forbidden-knowledge',
        name: 'Apocrypha',
        subtitle: 'Forbidden knowledge & esoteric lore',
        wallColor: '#2a2230',
        accentColor: '#b388ff',
        floorMaterial: 'concrete',
        lightColor: '#d4c8ff',
        lightIntensity: 0.95,
        ceiling: 6.2,
        font: 'fraktur',
        titleLetterSpacing: 0.05,
        audioTone: {
            baseHz: 41,
            partials: [1, 1.01, 1.99, 2.98, 4.5],
            lfoHz: 0.035,
            noiseCenterHz: 380,
            noiseGain: 0.08,
            bellRatio: 5.3,
            bellEverySec: 27,
        },
        infographic: {
            title: 'TREE OF NAMES',
            body: [
                'KETHER',
                '  the silence before breath',
                'CHOKMAH',
                '  the first lie, still true',
                'BINAH',
                '  the womb that remembers',
                'TIPHERETH',
                '  the face under faces',
                '',
                'do not read aloud.',
            ],
        },
    },
    // Room 4 - scripted milestone. The ambient engine recognises this theme id
    // and goes completely silent; the room is lined with a ring of suited
    // watchers that always track the player's head. The infographic is
    // terse by design; speak softly, or not at all.
    {
        id: 'silence',
        name: 'The Silence',
        subtitle: 'please observe the observers',
        wallColor: '#16161a',
        accentColor: '#e4e0d2',
        floorMaterial: 'concrete',
        lightColor: '#d4d0c4',
        lightIntensity: 0.55,
        ceiling: 6.4,
        font: 'major-mono',
        titleLetterSpacing: 0.45,
        audioTone: {
            // Effectively silent; the audio engine also hard-mutes on 'silence'.
            baseHz: 24,
            partials: [1],
            lfoHz: 0.01,
            noiseCenterHz: 120,
            noiseGain: 0,
            bellRatio: 2,
            bellEverySec: 999,
        },
        infographic: {
            title: 'RULES OF VISIT',
            body: [
                'do not speak.',
                'do not whistle.',
                'do not hum.',
                '',
                'the men will remain.',
                'they will remember',
                'whichever face you wear',
                'when you leave.',
            ],
        },
    },
];

const PROCEDURAL_THEMES: Theme[] = [
    {
        id: 'mycelium-cathedral',
        name: 'Mycelium Cathedral',
        subtitle: 'the quiet network under the world',
        wallColor: '#2f3a2c',
        accentColor: '#a8d580',
        floorMaterial: 'carpet',
        lightColor: '#c6ffb0',
        lightIntensity: 0.7,
        ceiling: 7.5,
        font: 'cormorant',
        audioTone: {
            baseHz: 49,
            partials: [1, 1.5, 2.0, 2.5, 3.0],
            lfoHz: 0.04,
            noiseCenterHz: 620,
            noiseGain: 0.1,
            bellRatio: 4,
            bellEverySec: 24,
        },
        infographic: {
            title: 'THE UNDERSONG',
            body: [
                'each thread is a sentence',
                'each sentence was older',
                'than soil',
                '',
                'we were not the authors.',
                'we were the page.',
            ],
        },
    },
    {
        id: 'mirror-loop',
        name: 'Mirror Loop',
        subtitle: 'the reflection refuses to catch up',
        wallColor: '#e8e8ee',
        accentColor: '#ffffff',
        floorMaterial: 'tile',
        lightColor: '#ffffff',
        lightIntensity: 1.4,
        ceiling: 4.2,
        font: 'major-mono',
        titleLetterSpacing: 0.5,
        audioTone: {
            baseHz: 110,
            partials: [1, 2, 3, 4],
            lfoHz: 0.12,
            noiseCenterHz: 4200,
            noiseGain: 0.03,
            bellRatio: 8,
            bellEverySec: 14,
        },
        infographic: {
            title: 'FOLLOWERS',
            body: [
                'one behind you.',
                'one ahead of you.',
                'you are not the original.',
                'none of you are.',
            ],
        },
    },
    {
        id: 'infinite-library',
        name: 'Infinite Library',
        subtitle: 'every book is this one',
        wallColor: '#5a3a22',
        accentColor: '#d8a24c',
        floorMaterial: 'wood',
        lightColor: '#ffd88a',
        lightIntensity: 0.9,
        ceiling: 6.8,
        font: 'cormorant',
        audioTone: {
            baseHz: 65,
            partials: [1, 1.5, 2.0, 3.0, 4.5],
            lfoHz: 0.05,
            noiseCenterHz: 900,
            noiseGain: 0.06,
            bellRatio: 6,
            bellEverySec: 20,
        },
        infographic: {
            title: 'CATALOGUE',
            body: [
                'ISBN 000-0-000000-00-0',
                '"The Book You Are Inside"',
                'printed the year',
                'you were born',
                'author: a hand that was',
                'never yours',
            ],
        },
    },
    {
        id: 'drowned-office',
        name: 'The Drowned Office',
        subtitle: 'overtime, indefinitely',
        wallColor: '#a9b3b0',
        accentColor: '#6fc1c1',
        floorMaterial: 'carpet',
        lightColor: '#bfe9e8',
        lightIntensity: 0.95,
        ceiling: 3.4,
        font: 'plex-mono',
        audioTone: {
            baseHz: 44,
            partials: [1, 1.008, 2.01, 3.02],
            lfoHz: 0.045,
            noiseCenterHz: 280,
            noiseGain: 0.09,
            bellRatio: 3.3,
            bellEverySec: 30,
        },
        infographic: {
            title: 'Q4 PROJECTIONS',
            body: [
                'REVENUE ............ -',
                'PRESENCE ........... -',
                'UNACCOUNTED ...... 27',
                '',
                'the water never left.',
                'we got used to it.',
            ],
        },
    },
    {
        id: 'tangerine-void',
        name: 'Tangerine Void',
        subtitle: 'an impossible evening',
        wallColor: '#3a1a12',
        accentColor: '#ff8a3d',
        floorMaterial: 'concrete',
        lightColor: '#ffb070',
        lightIntensity: 1.2,
        ceiling: 5.6,
        font: 'syne-mono',
        audioTone: {
            baseHz: 52,
            partials: [1, 1.333, 2.0, 2.667],
            lfoHz: 0.07,
            noiseCenterHz: 1300,
            noiseGain: 0.07,
            bellRatio: 5,
            bellEverySec: 19,
        },
        infographic: {
            title: 'DUSK, HELD',
            body: [
                'the sun stopped',
                'and nobody noticed',
                'for a long time',
                '',
                'the tangerines',
                'are not real.',
                'they taste correct.',
            ],
        },
    },
    {
        id: 'hall-of-unfinished-prayers',
        name: 'Hall of Unfinished Prayers',
        subtitle: '...and then -',
        wallColor: '#cfc8b8',
        accentColor: '#e5d28c',
        floorMaterial: 'tile',
        lightColor: '#fff0c0',
        lightIntensity: 0.65,
        ceiling: 7.0,
        font: 'cormorant',
        bodyAlign: 'left',
        audioTone: {
            baseHz: 46,
            partials: [1, 1.5, 3.0, 4.5],
            lfoHz: 0.03,
            noiseCenterHz: 520,
            noiseGain: 0.07,
            bellRatio: 4,
            bellEverySec: 31,
        },
        infographic: {
            title: 'UNFINISHED',
            body: [
                'please, if you are -',
                'i only wanted to -',
                'keep her safe, keep the -',
                'amen, amen, am-',
            ],
        },
    },
    {
        id: 'static-cathedral',
        name: 'Static Cathedral',
        subtitle: 'a choir of broken antennas',
        wallColor: '#26262a',
        accentColor: '#9fe8ff',
        floorMaterial: 'concrete',
        lightColor: '#c6f4ff',
        lightIntensity: 0.55,
        ceiling: 6.5,
        font: 'major-mono',
        titleLetterSpacing: 0.3,
        audioTone: {
            baseHz: 37,
            partials: [1, 1.5, 2.01, 3.02, 7],
            lfoHz: 0.16,
            noiseCenterHz: 3200,
            noiseGain: 0.18,
            bellRatio: 11,
            bellEverySec: 12,
        },
        infographic: {
            title: 'TRANSMISSION',
            body: [
                '-.- -- ... -',
                'freq: unassigned',
                'duration: ongoing',
                '',
                '"...and we are still',
                ' sending..."',
            ],
        },
    },
    {
        id: 'bone-orchard',
        name: 'Bone Orchard',
        subtitle: 'the harvest smiled back',
        wallColor: '#d7cfc0',
        accentColor: '#e9dcc3',
        floorMaterial: 'wood',
        lightColor: '#fff0d8',
        lightIntensity: 0.85,
        ceiling: 5.5,
        font: 'cinzel',
        titleLetterSpacing: 0.35,
        audioTone: {
            baseHz: 54,
            partials: [1, 1.5, 2.0, 3.0],
            lfoHz: 0.04,
            noiseCenterHz: 800,
            noiseGain: 0.07,
            bellRatio: 5.5,
            bellEverySec: 23,
        },
        infographic: {
            title: 'SEASON',
            body: [
                'planted: before memory',
                'bloomed: slowly',
                'harvested: ourselves',
            ],
        },
    },
    {
        id: 'red-vending',
        name: 'Red Vending Corridor',
        subtitle: 'everything costs exactly one',
        wallColor: '#9a1c1c',
        accentColor: '#ffcf40',
        floorMaterial: 'vinyl',
        lightColor: '#ffd2b0',
        lightIntensity: 1.0,
        ceiling: 3.2,
        font: 'major-mono',
        audioTone: {
            baseHz: 61,
            partials: [1, 2, 3, 5],
            lfoHz: 0.11,
            noiseCenterHz: 1400,
            noiseGain: 0.06,
            bellRatio: 6,
            bellEverySec: 16,
        },
        infographic: {
            title: 'MENU',
            body: [
                'A1 friday evening',
                'B3 someone\'s kitchen',
                'C2 being eight again',
                'D4 sold out',
            ],
        },
    },
    {
        id: 'hollow-saint',
        name: 'Hollow Saint',
        subtitle: 'faith with nobody home',
        wallColor: '#eae5d8',
        accentColor: '#d9b875',
        floorMaterial: 'tile',
        lightColor: '#ffeac0',
        lightIntensity: 0.8,
        ceiling: 7.8,
        font: 'unifraktur',
        titleLetterSpacing: 0.05,
        audioTone: {
            baseHz: 39,
            partials: [1, 1.5, 2.0, 3.0, 4.5, 6.0],
            lfoHz: 0.025,
            noiseCenterHz: 480,
            noiseGain: 0.06,
            bellRatio: 3,
            bellEverySec: 33,
        },
        infographic: {
            title: 'RELIQUARY',
            body: [
                'contents: one silence',
                'condition: intact',
                '',
                'do not open.',
                'you are inside.',
            ],
        },
    },
    {
        id: 'last-color',
        name: 'The Last Color',
        subtitle: 'a hue that was removed',
        wallColor: '#8c88a0',
        accentColor: '#ff00c8',
        floorMaterial: 'vinyl',
        lightColor: '#ffb4ff',
        lightIntensity: 1.0,
        ceiling: 4.0,
        font: 'syne-mono',
        audioTone: {
            baseHz: 94,
            partials: [1, 1.0595, 2.0, 2.38, 3.56],
            lfoHz: 0.18,
            noiseCenterHz: 5200,
            noiseGain: 0.04,
            bellRatio: 9,
            bellEverySec: 13,
        },
        infographic: {
            title: 'REDACTED',
            body: [
                'once, there were eight',
                'primary colors.',
                'we do not speak',
                'of the eighth.',
                '',
                'try not to focus on it.',
            ],
        },
    },
    {
        id: 'carpet-forever',
        name: 'Carpet Forever',
        subtitle: 'pattern, pattern, pattern',
        wallColor: '#b09b6e',
        accentColor: '#e0c27a',
        floorMaterial: 'carpet',
        lightColor: '#fff1c0',
        lightIntensity: 1.05,
        ceiling: 3.6,
        font: 'space-mono',
        audioTone: {
            baseHz: 67,
            partials: [1, 2.0, 3.0, 4.0],
            lfoHz: 0.08,
            noiseCenterHz: 2000,
            noiseGain: 0.05,
            bellRatio: 6.5,
            bellEverySec: 17,
        },
        infographic: {
            title: 'MOTIF',
            body: [
                'the pattern does not',
                'repeat.',
                'we only remember',
                'it does.',
                '',
                'count the diamonds.',
                'you cannot.',
            ],
        },
    },
    {
        id: 'tiled-sea',
        name: 'Tiled Sea',
        subtitle: 'an ocean at 6,400 tiles',
        wallColor: '#a9d9e3',
        accentColor: '#006e89',
        floorMaterial: 'tile',
        lightColor: '#d0f0ff',
        lightIntensity: 1.15,
        ceiling: 4.4,
        font: 'cinzel',
        audioTone: {
            baseHz: 50,
            partials: [1, 1.5, 2.0, 3.0],
            lfoHz: 0.06,
            noiseCenterHz: 900,
            noiseGain: 0.08,
            bellRatio: 5,
            bellEverySec: 21,
        },
        infographic: {
            title: 'BATHYMETRY',
            body: [
                'depth: three grout-lines',
                'current: none detected',
                '',
                'something is',
                'under the pool.',
                'it is not interested',
                'in us.',
            ],
        },
    },
    // -----------------------------------------------------------------------
    // Expansion pool - the 26 themes that tripled the procedural variety. They
    // are listed in rough "least -> most uncanny" order, though the
    // never-repeat picker shuffles them freely.
    // -----------------------------------------------------------------------
    {
        id: 'pool-at-midnight',
        name: 'Pool At Midnight',
        subtitle: 'the water is always exactly tepid',
        wallColor: '#1e4c66',
        accentColor: '#9adff0',
        floorMaterial: 'tile',
        lightColor: '#a6e1ff',
        lightIntensity: 0.85,
        ceiling: 5.5,
        font: 'cormorant',
        audioTone: {
            baseHz: 46,
            partials: [1, 1.5, 2.0, 3.0],
            lfoHz: 0.07,
            noiseCenterHz: 520,
            noiseGain: 0.09,
            bellRatio: 5,
            bellEverySec: 22,
        },
        infographic: {
            title: 'LANE FOUR',
            body: [
                'hours: never',
                'depth: consistent',
                'swimmers: see below',
                '',
                'a lane is occupied',
                'that has always been',
                'occupied.',
            ],
        },
    },
    {
        id: 'server-farm',
        name: 'Cold Aisle',
        subtitle: 'they kept running after we left',
        wallColor: '#1c1f26',
        accentColor: '#47ffb8',
        floorMaterial: 'vinyl',
        lightColor: '#a2ffe0',
        lightIntensity: 0.6,
        ceiling: 3.4,
        font: 'plex-mono',
        audioTone: {
            baseHz: 58,
            partials: [1, 2.0, 3.0, 4.0, 5.0],
            lfoHz: 0.14,
            noiseCenterHz: 3800,
            noiseGain: 0.14,
            bellRatio: 9,
            bellEverySec: 11,
        },
        infographic: {
            title: 'UPTIME',
            body: [
                'BOOT:   ??/??/????',
                'UPTIME: 999999 days',
                'LOAD:   0.00',
                '',
                'nothing is being',
                'computed.',
                'but it is being',
                'computed correctly.',
            ],
        },
    },
    {
        id: 'dental-suite',
        name: 'Dental Suite 3',
        subtitle: 'open wide, please',
        wallColor: '#eaeef0',
        accentColor: '#8ec5e8',
        floorMaterial: 'vinyl',
        lightColor: '#ffffff',
        lightIntensity: 1.35,
        ceiling: 2.9,
        font: 'space-mono',
        audioTone: {
            baseHz: 84,
            partials: [1, 1.5, 2.5, 4.0],
            lfoHz: 0.22,
            noiseCenterHz: 2200,
            noiseGain: 0.1,
            bellRatio: 10,
            bellEverySec: 13,
        },
        infographic: {
            title: 'APPT. LOG',
            body: [
                '2:00  you',
                '2:30  you (again)',
                '3:00  you (younger)',
                '3:30  you (not yet)',
                '',
                'spit when ready.',
            ],
        },
    },
    {
        id: 'parking-garage',
        name: 'Sublevel P-6',
        subtitle: 'sodium light, forever on',
        wallColor: '#4a4740',
        accentColor: '#ffb356',
        floorMaterial: 'concrete',
        lightColor: '#ffc878',
        lightIntensity: 0.9,
        ceiling: 2.8,
        font: 'plex-mono',
        audioTone: {
            baseHz: 41,
            partials: [1, 1.01, 2.0, 3.02],
            lfoHz: 0.05,
            noiseCenterHz: 340,
            noiseGain: 0.1,
            bellRatio: 3.3,
            bellEverySec: 28,
        },
        infographic: {
            title: 'LEVEL P-6',
            body: [
                'SPACES: 214',
                'OCCUPIED: 214',
                'VEHICLES: 0',
                '',
                'the cars left',
                'the engines still',
                'run somewhere',
            ],
        },
    },
    {
        id: 'waiting-room-eternal',
        name: 'Intake',
        subtitle: 'please have a seat',
        wallColor: '#d8cfbb',
        accentColor: '#7aa3a7',
        floorMaterial: 'carpet',
        lightColor: '#f4ead2',
        lightIntensity: 1.05,
        ceiling: 3.0,
        font: 'plex-mono',
        audioTone: {
            baseHz: 63,
            partials: [1, 2.0, 3.0, 5.0],
            lfoHz: 0.08,
            noiseCenterHz: 1800,
            noiseGain: 0.05,
            bellRatio: 7,
            bellEverySec: 24,
        },
        infographic: {
            title: 'NOW SERVING',
            body: [
                'NOW SERVING: 00',
                'YOUR NUMBER: 7481',
                'EST. WAIT: -',
                '',
                'we will call your name.',
                'we have many names for you.',
            ],
        },
    },
    {
        id: 'observation-mirror',
        name: 'Room With A View',
        subtitle: 'two-way, both ways',
        wallColor: '#1f2028',
        accentColor: '#b8b8d0',
        floorMaterial: 'vinyl',
        lightColor: '#c0c0e0',
        lightIntensity: 0.7,
        ceiling: 3.6,
        font: 'major-mono',
        titleLetterSpacing: 0.3,
        audioTone: {
            baseHz: 55,
            partials: [1, 1.01, 2.02, 3.0],
            lfoHz: 0.06,
            noiseCenterHz: 1200,
            noiseGain: 0.07,
            bellRatio: 6.5,
            bellEverySec: 19,
        },
        infographic: {
            title: 'SUBJECT',
            body: [
                'OBSERVED: yes',
                'OBSERVING: yes',
                'SAMPLE #: you',
                '',
                'they are taking',
                'excellent notes.',
            ],
        },
    },
    {
        id: 'preservation-jars',
        name: 'Specimen Gallery',
        subtitle: 'pale things in amber fluid',
        wallColor: '#3d342a',
        accentColor: '#ffd478',
        floorMaterial: 'wood',
        lightColor: '#ffe0a0',
        lightIntensity: 0.65,
        ceiling: 4.2,
        font: 'cormorant',
        audioTone: {
            baseHz: 42,
            partials: [1, 1.5, 2.0, 3.0, 4.5],
            lfoHz: 0.035,
            noiseCenterHz: 480,
            noiseGain: 0.08,
            bellRatio: 4.2,
            bellEverySec: 26,
        },
        infographic: {
            title: 'JAR 47B',
            body: [
                'label: illegible',
                'contents: 1 (one)',
                'condition: awake',
                '',
                'blinks, rarely.',
                'please do not tap.',
            ],
        },
    },
    {
        id: 'wax-museum',
        name: 'Wax Figures',
        subtitle: 'everyone mid-gesture',
        wallColor: '#352c24',
        accentColor: '#f5d08a',
        floorMaterial: 'wood',
        lightColor: '#ffe8b0',
        lightIntensity: 0.85,
        ceiling: 4.6,
        font: 'cinzel',
        titleLetterSpacing: 0.2,
        audioTone: {
            baseHz: 52,
            partials: [1, 1.5, 2.0, 3.0],
            lfoHz: 0.03,
            noiseCenterHz: 640,
            noiseGain: 0.06,
            bellRatio: 5,
            bellEverySec: 25,
        },
        infographic: {
            title: 'LIKENESS',
            body: [
                'poured: 1889',
                'cooled: never',
                'subject: you',
                '',
                'slight change in',
                'the expression',
                'between visits.',
            ],
        },
    },
    {
        id: 'cold-storage',
        name: 'Cold Storage',
        subtitle: 'minus forty, year after year',
        wallColor: '#c9d4d8',
        accentColor: '#7fd2e8',
        floorMaterial: 'concrete',
        lightColor: '#d8f0ff',
        lightIntensity: 0.9,
        ceiling: 4.0,
        font: 'plex-mono',
        audioTone: {
            baseHz: 48,
            partials: [1, 2.01, 3.0, 4.0],
            lfoHz: 0.09,
            noiseCenterHz: 2800,
            noiseGain: 0.12,
            bellRatio: 6,
            bellEverySec: 18,
        },
        infographic: {
            title: 'INVENTORY',
            body: [
                'ITEM: 1',
                'TEMP: -41 C',
                'LABEL: "ME"',
                '',
                'still, after all this,',
                'you are the oldest',
                'thing inside.',
            ],
        },
    },
    {
        id: 'subway-afterhours',
        name: 'Platform 0',
        subtitle: 'the last train was not',
        wallColor: '#2a2d33',
        accentColor: '#ffd64a',
        floorMaterial: 'concrete',
        lightColor: '#ffeeaa',
        lightIntensity: 0.7,
        ceiling: 4.2,
        font: 'plex-mono',
        audioTone: {
            baseHz: 36,
            partials: [1, 1.5, 2.0, 3.0, 5.0],
            lfoHz: 0.045,
            noiseCenterHz: 460,
            noiseGain: 0.11,
            bellRatio: 3.7,
            bellEverySec: 21,
        },
        infographic: {
            title: 'SCHEDULE',
            body: [
                'NORTHBOUND: -',
                'SOUTHBOUND: -',
                'INBOUND:   soon',
                '',
                'stand behind',
                'the yellow line',
                'you will feel it',
            ],
        },
    },
    {
        id: 'abandoned-greenhouse',
        name: 'Greenhouse 12',
        subtitle: 'things kept growing',
        wallColor: '#2d4438',
        accentColor: '#b8e67b',
        floorMaterial: 'concrete',
        lightColor: '#d2f0b4',
        lightIntensity: 0.8,
        ceiling: 6.2,
        font: 'cormorant',
        audioTone: {
            baseHz: 54,
            partials: [1, 1.5, 2.0, 2.667, 4.0],
            lfoHz: 0.055,
            noiseCenterHz: 900,
            noiseGain: 0.1,
            bellRatio: 4.5,
            bellEverySec: 23,
        },
        infographic: {
            title: 'SEED LOG',
            body: [
                'planted: lost',
                'species: unknown',
                'harvest: refused',
                '',
                'the vines made',
                'a door-shape',
                'in the glass.',
            ],
        },
    },
    {
        id: 'clockwork-atrium',
        name: 'Clockwork Atrium',
        subtitle: 'every gear remembers',
        wallColor: '#4a3a24',
        accentColor: '#d9b256',
        floorMaterial: 'wood',
        lightColor: '#ffd794',
        lightIntensity: 0.9,
        ceiling: 7.8,
        font: 'cinzel',
        titleLetterSpacing: 0.25,
        audioTone: {
            baseHz: 60,
            partials: [1, 2.0, 3.0, 4.0, 6.0],
            lfoHz: 0.1,
            noiseCenterHz: 1600,
            noiseGain: 0.06,
            bellRatio: 6,
            bellEverySec: 14,
        },
        infographic: {
            title: 'ESCAPEMENT',
            body: [
                'tick: affirm',
                'tock: refuse',
                'tick: affirm',
                '',
                'the minute hand',
                'has opinions',
                'about you',
            ],
        },
    },
    {
        id: 'radio-relay',
        name: 'Relay Station',
        subtitle: 'a signal, still outbound',
        wallColor: '#2a2e31',
        accentColor: '#ff7a56',
        floorMaterial: 'vinyl',
        lightColor: '#ffb68a',
        lightIntensity: 0.7,
        ceiling: 3.6,
        font: 'plex-mono',
        audioTone: {
            baseHz: 71,
            partials: [1, 2.0, 3.0, 5.0, 7.0],
            lfoHz: 0.18,
            noiseCenterHz: 2600,
            noiseGain: 0.16,
            bellRatio: 11,
            bellEverySec: 10,
        },
        infographic: {
            title: 'BROADCAST',
            body: [
                'FREQ: 1420.40 MHz',
                'POWER: measurable',
                'REPLY: never',
                '',
                'we are the reply',
                'we just haven\'t',
                'reached ourselves yet',
            ],
        },
    },
    {
        id: 'museum-of-rust',
        name: 'Museum of Rust',
        subtitle: 'oxidation, from atoms to worlds',
        wallColor: '#3e2218',
        accentColor: '#ff8544',
        floorMaterial: 'concrete',
        lightColor: '#ffb884',
        lightIntensity: 0.95,
        ceiling: 6.0,
        font: 'cinzel',
        titleLetterSpacing: 0.22,
        audioTone: {
            baseHz: 42,
            partials: [1, 1.5, 2.0, 3.0, 4.5],
            lfoHz: 0.035,
            noiseCenterHz: 620,
            noiseGain: 0.09,
            bellRatio: 4.8,
            bellEverySec: 24,
        },
        infographic: {
            title: 'OXIDATION',
            body: [
                '4 Fe + 3 O\u2082  \u2192  2 Fe\u2082O\u2083',
                '',
                'SPECIMEN: Mars',
                '  radius  3,389 km',
                '  gravity 0.38 g',
                '  sky     butterscotch',
                '  soil    rusted through',
                '',
                'MOONS:',
                '  Phobos  22 km   7.66 h',
                '  Deimos  12 km  30.31 h',
                '',
                'a whole world',
                'is returning home.',
            ],
        },
    },
    {
        id: 'motel-203',
        name: 'Room 203',
        subtitle: 'vacancy: yes. tenants: several.',
        wallColor: '#6a4a38',
        accentColor: '#ff4d6a',
        floorMaterial: 'carpet',
        lightColor: '#ffb496',
        lightIntensity: 0.75,
        ceiling: 2.7,
        font: 'syne-mono',
        audioTone: {
            baseHz: 53,
            partials: [1, 1.5, 2.0, 3.0, 4.0],
            lfoHz: 0.075,
            noiseCenterHz: 1100,
            noiseGain: 0.08,
            bellRatio: 5.3,
            bellEverySec: 22,
        },
        infographic: {
            title: 'CHECK IN',
            body: [
                'ARR: yesterday',
                'DEP: unset',
                'PARTY OF: it depends',
                '',
                'the ice machine',
                'is always just',
                'around the corner',
            ],
        },
    },
    {
        id: 'corridor-to-self',
        name: 'Corridor To Self',
        subtitle: 'every door is a mirror',
        wallColor: '#33333a',
        accentColor: '#ffffff',
        floorMaterial: 'tile',
        lightColor: '#e0e0f0',
        lightIntensity: 1.2,
        ceiling: 3.5,
        font: 'major-mono',
        titleLetterSpacing: 0.4,
        audioTone: {
            baseHz: 98,
            partials: [1, 2.0, 3.0, 5.0],
            lfoHz: 0.15,
            noiseCenterHz: 5200,
            noiseGain: 0.04,
            bellRatio: 8,
            bellEverySec: 12,
        },
        infographic: {
            title: 'DOORS',
            body: [
                'door 1: you',
                'door 2: you',
                'door 3: you',
                '',
                'pick any door.',
                'we already know',
                'which you pick.',
            ],
        },
    },
    {
        id: 'anechoic-foam',
        name: 'Anechoic Chamber',
        subtitle: 'a room without echoes',
        wallColor: '#1a1a1f',
        accentColor: '#7e7e92',
        floorMaterial: 'vinyl',
        lightColor: '#9e9eb2',
        lightIntensity: 0.4,
        ceiling: 3.2,
        font: 'plex-mono',
        audioTone: {
            baseHz: 28,
            partials: [1, 1.5],
            lfoHz: 0.02,
            noiseCenterHz: 180,
            noiseGain: 0.03,
            bellRatio: 2.5,
            bellEverySec: 45,
        },
        infographic: {
            title: 'SILENCE',
            body: [
                'REFLECTION: 0 dB',
                'SELF-NOISE:',
                '  your heart',
                '  your blood',
                '  something else',
                '',
                'the third sound',
                'is not yours.',
            ],
        },
    },
    {
        id: 'taxidermy-lounge',
        name: 'Taxidermy Lounge',
        subtitle: 'still, politely',
        wallColor: '#3c2e1d',
        accentColor: '#c7965a',
        floorMaterial: 'carpet',
        lightColor: '#ffca92',
        lightIntensity: 0.7,
        ceiling: 4.0,
        font: 'cormorant',
        audioTone: {
            baseHz: 50,
            partials: [1, 1.5, 2.0, 3.0],
            lfoHz: 0.035,
            noiseCenterHz: 520,
            noiseGain: 0.07,
            bellRatio: 5,
            bellEverySec: 27,
        },
        infographic: {
            title: 'COLLECTION',
            body: [
                'specimen: 1',
                'pose: contemplative',
                'breath: no',
                '',
                'it turned to face you',
                'the last time',
                'you looked away.',
            ],
        },
    },
    {
        id: 'nursery-frozen',
        name: 'The Nursery',
        subtitle: 'waiting for someone',
        wallColor: '#e4c8d4',
        accentColor: '#ffa0b8',
        floorMaterial: 'carpet',
        lightColor: '#ffdce6',
        lightIntensity: 0.75,
        ceiling: 2.8,
        font: 'cormorant',
        audioTone: {
            baseHz: 72,
            partials: [1, 2.0, 3.0, 5.0],
            lfoHz: 0.11,
            noiseCenterHz: 1800,
            noiseGain: 0.05,
            bellRatio: 7.5,
            bellEverySec: 17,
        },
        infographic: {
            title: 'LULLABY',
            body: [
                'rock-a-bye, almost',
                'rock-a-bye, soon',
                '',
                'the mobile still turns.',
                'no one wound it.',
            ],
        },
    },
    {
        id: 'phonograph-archive',
        name: 'Phonograph Archive',
        subtitle: 'voices preserved against permission',
        wallColor: '#44361e',
        accentColor: '#e8b456',
        floorMaterial: 'wood',
        lightColor: '#ffdc8a',
        lightIntensity: 0.75,
        ceiling: 4.4,
        font: 'cinzel',
        audioTone: {
            baseHz: 56,
            partials: [1, 1.5, 2.0, 3.0, 4.5],
            lfoHz: 0.06,
            noiseCenterHz: 1500,
            noiseGain: 0.09,
            bellRatio: 5.5,
            bellEverySec: 19,
        },
        infographic: {
            title: 'CYLINDER 113',
            body: [
                'recorded: 1906',
                'voice: unidentified',
                'laughter: yes',
                '',
                'it laughs at the same',
                'part each time.',
                'it is not the joke.',
            ],
        },
    },
    {
        id: 'art-gallery-wrong',
        name: 'Gallery (Wrong)',
        subtitle: 'the paintings finished themselves',
        wallColor: '#f0eadb',
        accentColor: '#8f6b3a',
        floorMaterial: 'wood',
        lightColor: '#fff4d8',
        lightIntensity: 1.0,
        ceiling: 5.2,
        font: 'cinzel',
        titleLetterSpacing: 0.15,
        audioTone: {
            baseHz: 62,
            partials: [1, 1.5, 2.0, 3.0],
            lfoHz: 0.05,
            noiseCenterHz: 1100,
            noiseGain: 0.06,
            bellRatio: 6,
            bellEverySec: 20,
        },
        infographic: {
            title: 'THIS GALLERY',
            body: [
                'subject: visitor',
                'medium: oil on canvas',
                'completion: ongoing',
                '',
                'you will model',
                'for the rest',
                'of the day.',
            ],
        },
    },
    {
        id: 'locker-room-endless',
        name: 'Locker Room',
        subtitle: 'steam, but no shower',
        wallColor: '#7a8a82',
        accentColor: '#c9dacc',
        floorMaterial: 'tile',
        lightColor: '#dfe8e2',
        lightIntensity: 1.05,
        ceiling: 3.1,
        font: 'plex-mono',
        audioTone: {
            baseHz: 58,
            partials: [1, 1.5, 2.0, 3.0],
            lfoHz: 0.08,
            noiseCenterHz: 1600,
            noiseGain: 0.12,
            bellRatio: 6,
            bellEverySec: 18,
        },
        infographic: {
            title: 'LOCKER 7',
            body: [
                'combination: yours',
                'contents: clothes',
                'size: close enough',
                '',
                'someone has',
                'already showered.',
                'the floor remembers.',
            ],
        },
    },
    {
        id: 'hospital-wing',
        name: 'Ward C',
        subtitle: 'visitation hours: ambiguous',
        wallColor: '#dadfd8',
        accentColor: '#7ac9b0',
        floorMaterial: 'vinyl',
        lightColor: '#eaf8ef',
        lightIntensity: 1.2,
        ceiling: 2.95,
        font: 'plex-mono',
        audioTone: {
            baseHz: 80,
            partials: [1, 2.0, 3.0, 4.0, 6.0],
            lfoHz: 0.17,
            noiseCenterHz: 2400,
            noiseGain: 0.08,
            bellRatio: 10,
            bellEverySec: 13,
        },
        infographic: {
            title: 'CHART',
            body: [
                'patient: YOU',
                'chief complaint: -',
                'vitals: stable, unattended',
                '',
                'the call light',
                'blinks in a rhythm',
                'of its own choosing.',
            ],
        },
    },
    {
        id: 'observatory-room',
        name: 'Observatory',
        subtitle: 'the stars were different yesterday',
        wallColor: '#181830',
        accentColor: '#b8c0ff',
        floorMaterial: 'wood',
        lightColor: '#c4c8ff',
        lightIntensity: 0.55,
        ceiling: 6.8,
        font: 'cinzel',
        titleLetterSpacing: 0.3,
        audioTone: {
            baseHz: 39,
            partials: [1, 1.5, 2.0, 3.0, 5.0],
            lfoHz: 0.03,
            noiseCenterHz: 380,
            noiseGain: 0.07,
            bellRatio: 4,
            bellEverySec: 29,
        },
        infographic: {
            title: 'ALMANAC',
            body: [
                'constellations: 87',
                'new constellations: 1',
                '',
                'it was not',
                'there last night.',
                'it knows your name.',
            ],
        },
    },
    {
        id: 'dripping-chapel',
        name: 'The Dripping Chapel',
        subtitle: 'wet stone, wet prayer',
        wallColor: '#3a4540',
        accentColor: '#94b0a0',
        floorMaterial: 'concrete',
        lightColor: '#c6d8c8',
        lightIntensity: 0.6,
        ceiling: 8.0,
        font: 'unifraktur',
        titleLetterSpacing: 0.05,
        audioTone: {
            baseHz: 37,
            partials: [1, 1.5, 2.0, 2.667, 4.0],
            lfoHz: 0.025,
            noiseCenterHz: 400,
            noiseGain: 0.1,
            bellRatio: 3.5,
            bellEverySec: 24,
        },
        infographic: {
            title: 'VOTIVE',
            body: [
                'candle: extinguished',
                'prayer: partial',
                'echo: overgrown',
                '',
                'something listened',
                'and took notes.',
            ],
        },
    },
    {
        id: 'childhood-wrong',
        name: 'Childhood Bedroom',
        subtitle: 'almost exactly right',
        wallColor: '#b8cedb',
        accentColor: '#f4c068',
        floorMaterial: 'carpet',
        lightColor: '#ffe1a8',
        lightIntensity: 0.85,
        ceiling: 2.6,
        font: 'cormorant',
        audioTone: {
            baseHz: 67,
            partials: [1, 2.0, 3.0, 5.0],
            lfoHz: 0.09,
            noiseCenterHz: 1700,
            noiseGain: 0.05,
            bellRatio: 7,
            bellEverySec: 18,
        },
        infographic: {
            title: 'INVENTORY',
            body: [
                'bed: yes',
                'window: wrong wall',
                'glow stars: different',
                'poster: you never had',
                '',
                'it is almost',
                'exactly',
                'right.',
            ],
        },
    },
    {
        id: 'wallpaper-archive',
        name: 'Wallpaper Archive',
        subtitle: 'patterns from dead decades',
        wallColor: '#c9a475',
        accentColor: '#8d4f3c',
        floorMaterial: 'carpet',
        lightColor: '#ffdcb0',
        lightIntensity: 0.95,
        ceiling: 3.0,
        font: 'syne-mono',
        audioTone: {
            baseHz: 68,
            partials: [1, 2.0, 3.0, 4.0],
            lfoHz: 0.08,
            noiseCenterHz: 1900,
            noiseGain: 0.05,
            bellRatio: 6.5,
            bellEverySec: 18,
        },
        infographic: {
            title: 'CATALOG',
            body: [
                '1962  honeycomb',
                '1973  velvet paisley',
                '1984  pastel grid',
                '????  the one',
                '      with the eyes',
                '',
                'please do not',
                'stare back.',
            ],
        },
    },
    {
        id: 'gravity-adjusted',
        name: 'Gravity Adjusted',
        subtitle: 'the furniture is on the ceiling',
        wallColor: '#c4bdd0',
        accentColor: '#ffb04a',
        floorMaterial: 'tile',
        lightColor: '#ffdba0',
        lightIntensity: 0.95,
        ceiling: 4.0,
        font: 'major-mono',
        titleLetterSpacing: 0.25,
        audioTone: {
            baseHz: 59,
            partials: [1, 1.5, 2.0, 3.0, 4.5],
            lfoHz: 0.12,
            noiseCenterHz: 2100,
            noiseGain: 0.06,
            bellRatio: 5.5,
            bellEverySec: 15,
        },
        infographic: {
            title: 'ORIENTATION',
            body: [
                'down: unclear',
                'up: contested',
                '',
                'the chairs chose',
                'a different agreement.',
                'you may also,',
                'if you can.',
            ],
        },
    },
];

export const FRACTAL_CHAPEL_THEME: Theme = {
    id: 'fractal-chapel',
    name: 'Fractal Chapel',
    subtitle: 'pan-dimensional self-similarity',
    wallColor: '#0a0018',
    accentColor: '#ff38e2',
    floorMaterial: 'tile',
    lightColor: '#ffb0ff',
    lightIntensity: 0.4,
    ceiling: 8.8,
    font: 'cormorant',
    titleLetterSpacing: 0.4,
    audioTone: {
        baseHz: 33,
        partials: [1, 1.5, 2.0, 2.667, 4.0, 5.333, 8.0],
        lfoHz: 0.11,
        noiseCenterHz: 2200,
        noiseGain: 0.035,
        bellRatio: 3.333,
        bellEverySec: 14,
    },
    infographic: {
        title: 'SELF AS FRACTAL',
        body: [
            'the boundary',
            'was a costume.',
            '',
            'every face is',
            'every face.',
            'every eye is',
            'the first eye.',
            '',
            'welcome back.',
        ],
    },
};

export const MARINE_BIOLOGY_THEME: Theme = {
    id: 'marine-biology',
    name: 'Pelagic Hall',
    subtitle: 'specimens of the deep column',
    wallColor: '#1b3a4c',
    accentColor: '#6bd9c4',
    floorMaterial: 'concrete',
    lightColor: '#a8e6de',
    lightIntensity: 0.85,
    ceiling: 7.6,
    font: 'cormorant',
    titleLetterSpacing: 0.22,
    audioTone: {
        baseHz: 44,
        partials: [1, 1.5, 2.0, 3.0, 4.0],
        lfoHz: 0.05,
        noiseCenterHz: 420,
        noiseGain: 0.09,
        bellRatio: 4.75,
        bellEverySec: 19,
    },
    infographic: {
        title: 'MARINE BIOLOGY',
        body: [
            'SUNLIGHT ZONE   0-200m',
            'TWILIGHT        200-1000m',
            'MIDNIGHT        1000-4000m',
            'ABYSSAL         4000-6000m',
            'HADAL           6000-11000m',
            '',
            'pressure, patient.',
            'life, older than the sky.',
            '',
            'something still down there',
            'has never seen a face.',
        ],
    },
};

export const FOREST_GROVE_THEME: Theme = {
    id: 'forest-grove',
    name: 'The Grove',
    subtitle: 'a forest that appeared indoors',
    wallColor: '#0a1412',
    accentColor: '#c7d9ff',
    floorMaterial: 'concrete',
    lightColor: '#bcd0ff',
    lightIntensity: 0.25,
    ceiling: 18.0,
    font: 'cormorant',
    titleLetterSpacing: 0.2,
    audioTone: {
        // Nearly silent - the ForestRoom switches the engine into wind mode
        // and this under-bed is reduced anyway.
        baseHz: 30,
        partials: [1, 1.5],
        lfoHz: 0.02,
        noiseCenterHz: 900,
        noiseGain: 0.02,
        bellRatio: 2,
        bellEverySec: 60,
    },
    infographic: {
        title: 'THE GROVE',
        body: [
            'deciduous, probably',
            'moon: not a moon',
            'observers: several',
            '',
            'they step behind the trees',
            'when you turn your head.',
            'they are patient.',
        ],
    },
};

export const VOID_SHAFT_THEME: Theme = {
    id: 'void-shaft',
    name: 'The Drop',
    subtitle: 'there is no door out',
    wallColor: '#0c0a12',
    accentColor: '#9444ff',
    floorMaterial: 'concrete',
    lightColor: '#c9a8ff',
    lightIntensity: 0.55,
    ceiling: 6.0,
    font: 'major-mono',
    titleLetterSpacing: 0.4,
    audioTone: {
        baseHz: 31,
        partials: [1, 1.5, 2.0, 3.0, 5.0],
        lfoHz: 0.025,
        noiseCenterHz: 300,
        noiseGain: 0.08,
        bellRatio: 3.5,
        bellEverySec: 20,
    },
    infographic: {
        title: 'THE ONLY WAY',
        body: [
            'this room has no exit.',
            'the way forward is down.',
            '',
            'step into the hole.',
            'the set will fall away.',
            'trust the drop.',
        ],
    },
};

export const BRIDGE_OF_FACES_THEME: Theme = {
    id: 'bridge-of-faces',
    name: 'The Span of Witnesses',
    subtitle: 'a crossing observed',
    wallColor: '#111017',
    accentColor: '#3a3440',
    floorMaterial: 'concrete',
    lightColor: '#8089a0',
    lightIntensity: 0.28,
    ceiling: 16.0,
    font: 'major-mono',
    titleLetterSpacing: 0.38,
    audioTone: {
        baseHz: 26,
        partials: [1, 1.5, 2.0, 3.0, 5.0, 7.0],
        lfoHz: 0.025,
        noiseCenterHz: 180,
        noiseGain: 0.09,
        bellRatio: 4.1,
        bellEverySec: 26,
    },
    // Room 027 is intentionally silent on signage; no infographic is rendered.
    // These fields are retained for type safety but never displayed.
    infographic: {
        title: '',
        body: [],
    },
};

export const SOLAR_SYSTEM_THEME: Theme = {
    id: 'solar-system',
    name: 'Heliographic Hall',
    subtitle: 'scale model, not to scale',
    wallColor: '#05060b',
    accentColor: '#ffd488',
    floorMaterial: 'concrete',
    lightColor: '#ffe6b0',
    lightIntensity: 0.4,
    ceiling: 30.0,
    font: 'cormorant',
    titleLetterSpacing: 0.32,
    audioTone: {
        baseHz: 28,
        partials: [1, 1.5, 2.0, 3.0, 4.0, 6.0],
        lfoHz: 0.04,
        noiseCenterHz: 520,
        noiseGain: 0.05,
        bellRatio: 3.0,
        bellEverySec: 22,
    },
    infographic: {
        title: 'THE SOLAR SYSTEM',
        body: [
            '1  Mercury   - 0.39 AU',
            '2  Venus     - 0.72 AU',
            '3  Earth     - 1.00 AU',
            '4  Mars      - 1.52 AU',
            '5  Jupiter   - 5.20 AU',
            '6  Saturn    - 9.54 AU',
            '7  Uranus    - 19.2 AU',
            '8  Neptune   - 30.1 AU',
            '',
            'orbital count,',
            'at time of cataloguing:',
            'eight (8).',
            '',
            'do not count again.',
        ],
    },
};

// Themes pinned to specific section indices, regardless of seed.
// -  7  : Museum of Rust (planetary oxidation; centerpiece is Mars + moons)
// -  8  : Fractal Chapel (psychedelic milestone)
// - 14  : Marine Biology hall
// - 16  : The Grove (forest room - moonlit clearing, peeking watchers)
// - 21  : The Drop (sealed room - jump into the Mandelbrot to proceed)
// - 26  : Span of Witnesses (extreme-long bridge over a bottomless pit
//           flanked by rows of giant stone faces; falling off drops the
//           player into the same Mandelbrot cutscene as SECTION 022)
// - 32  : Heliographic Hall (solar system model + the one that doesn't belong)
//
// museum-of-rust is also pulled OUT of the procedural rotation because
// we promote it to a scripted Mars room; leaving it in the pool would let
// it reappear later with a generic rust artifact and contradict the
// pinned presentation.
const MUSEUM_OF_RUST_THEME: Theme = PROCEDURAL_THEMES.find(
    (t) => t.id === 'museum-of-rust',
)!;
export const MILESTONE_THEMES: Record<number, Theme> = {
    7: MUSEUM_OF_RUST_THEME,
    8: FRACTAL_CHAPEL_THEME,
    14: MARINE_BIOLOGY_THEME,
    16: FOREST_GROVE_THEME,
    21: VOID_SHAFT_THEME,
    26: BRIDGE_OF_FACES_THEME,
    32: SOLAR_SYSTEM_THEME,
};

export function pickProceduralTheme(rng: Rng, index: number): Theme {
    const cycle = PROCEDURAL_THEMES.length;
    const offset = (index + Math.floor(rand(rng, 0, cycle))) % cycle;
    return PROCEDURAL_THEMES[offset];
}

/**
 * Pick the theme for a section. When `usedThemeIds` is provided, procedural
 * picks skip any theme whose id has already appeared, so the player only sees
 * repeats once the entire pool has been exhausted (~40 rooms deep).
 */
export function getTheme(
    index: number,
    rng: Rng,
    usedThemeIds?: Set<ThemeId>,
): Theme {
    if (index < SCRIPTED_THEMES.length) {
        return SCRIPTED_THEMES[index];
    }
    if (MILESTONE_THEMES[index]) {
        return MILESTONE_THEMES[index];
    }
    if (usedThemeIds && usedThemeIds.size > 0) {
        const unused = PROCEDURAL_THEMES.filter((t) => !usedThemeIds.has(t.id));
        if (unused.length > 0) {
            return pick(rng, unused);
        }
    }
    if (rng() < 0.25) {
        return pick(rng, PROCEDURAL_THEMES);
    }
    return pickProceduralTheme(rng, index - SCRIPTED_THEMES.length);
}

export const THEME_IDS: ThemeId[] = [
    ...SCRIPTED_THEMES.map((t) => t.id),
    ...PROCEDURAL_THEMES.map((t) => t.id),
    FRACTAL_CHAPEL_THEME.id,
    MARINE_BIOLOGY_THEME.id,
    FOREST_GROVE_THEME.id,
    VOID_SHAFT_THEME.id,
    BRIDGE_OF_FACES_THEME.id,
    SOLAR_SYSTEM_THEME.id,
];
